### ISSUE TITLE
Using two TH02 Sensors

### ISSUE THREAD

**Issue by nilmother** [Seeed-Studio/Grove_Temper_Humidity#10]
Hi Guys,
I am pretty new to Arduino and I2C stuff in general.
Could someone give me a hint on how to use two TH02 sensors simultaneously?
I have one sitting on 0x40 and 0x68, but simply do not manage to address them indvidually.

Thanks a lot!!

**Comment by lakshanthad** [comment]
Hello,

Can I first know the development board you are connecting these sensors to?

Thank you.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
